-- =====================================================================
-- TutorBook - CMPE 172 Term Project - schema.sql
-- Loaded automatically on startup (spring.sql.init.mode=always).
-- Five entities: users, providers, services, availability_slots, appointments
-- =====================================================================

DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS availability_slots;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS users;

-- ---------------------------------------------------------------------
-- USERS: every person who can log in (customers AND providers/admins).
-- ---------------------------------------------------------------------
CREATE TABLE users (
    user_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    full_name      VARCHAR(120) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role  CHECK (role IN ('CUSTOMER', 'PROVIDER', 'ADMIN'))
);

-- ---------------------------------------------------------------------
-- PROVIDERS: the tutor profile of a user whose role is PROVIDER.
-- 1:1 with users (user_id is UNIQUE), so one login = at most one profile.
-- ---------------------------------------------------------------------
CREATE TABLE providers (
    provider_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    display_name   VARCHAR(120) NOT NULL,
    specialty      VARCHAR(120) NOT NULL,
    bio            VARCHAR(1000),
    CONSTRAINT uq_providers_user UNIQUE (user_id),
    CONSTRAINT fk_providers_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- SERVICES: catalog of tutoring session types (subject + length + price).
-- ---------------------------------------------------------------------
CREATE TABLE services (
    service_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(120)  NOT NULL,
    description       VARCHAR(1000),
    duration_minutes  INT           NOT NULL,
    price_cents       INT           NOT NULL,
    CONSTRAINT uq_services_name     UNIQUE (name),
    CONSTRAINT ck_services_duration CHECK (duration_minutes > 0),
    CONSTRAINT ck_services_price    CHECK (price_cents >= 0)
);

-- ---------------------------------------------------------------------
-- AVAILABILITY_SLOTS: a block of time a provider opens for one service.
-- ---------------------------------------------------------------------
CREATE TABLE availability_slots (
    slot_id      BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id  BIGINT    NOT NULL,
    service_id   BIGINT    NOT NULL,
    start_time   TIMESTAMP NOT NULL,
    end_time     TIMESTAMP NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_slots_provider FOREIGN KEY (provider_id)
        REFERENCES providers (provider_id) ON DELETE CASCADE,
    CONSTRAINT fk_slots_service  FOREIGN KEY (service_id)
        REFERENCES services (service_id),
    CONSTRAINT ck_slots_time     CHECK (end_time > start_time),
    -- A provider cannot open two slots that start at the same moment.
    CONSTRAINT uq_slots_provider_start UNIQUE (provider_id, start_time)
);

-- ---------------------------------------------------------------------
-- APPOINTMENTS: a customer's booking of one slot.
--
-- DOUBLE-BOOKING GUARD
--   active_slot_id is a generated column that equals slot_id while the
--   appointment is BOOKED and becomes NULL once it is CANCELLED.
--   The UNIQUE constraint on active_slot_id therefore allows at most ONE
--   active booking per slot, enforced by the database itself (so it also
--   holds when two requests race each other). Because a UNIQUE constraint
--   ignores NULLs, cancelled rows stay in the table as history and the
--   slot can be booked again.
-- ---------------------------------------------------------------------
CREATE TABLE appointments (
    appointment_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id         BIGINT      NOT NULL,
    customer_id     BIGINT      NOT NULL,
    status          VARCHAR(20) DEFAULT 'BOOKED' NOT NULL,
    notes           VARCHAR(500),
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cancelled_at    TIMESTAMP,
    active_slot_id  BIGINT GENERATED ALWAYS AS
                        (CASE WHEN status = 'BOOKED' THEN slot_id ELSE NULL END),
    CONSTRAINT fk_appt_slot     FOREIGN KEY (slot_id)
        REFERENCES availability_slots (slot_id),
    CONSTRAINT fk_appt_customer FOREIGN KEY (customer_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_appt_status   CHECK (status IN ('BOOKED', 'CANCELLED')),
    CONSTRAINT uq_appt_active_slot UNIQUE (active_slot_id)
);

-- Indexes for the most common lookups (browse slots, "my appointments").
CREATE INDEX idx_slots_start      ON availability_slots (start_time);
CREATE INDEX idx_slots_service    ON availability_slots (service_id);
CREATE INDEX idx_appt_customer    ON appointments (customer_id);
